### ISSUE TITLE
How to connect the Monsoon to the computer and check the connection is correct? 

### ISSUE THREAD

**Issue by sf-wind** [msoon/PyMonsoon#20]
In the python manual, there is no mention how the monsoon monitor to be connected to the computer and how to verify the connection is correct. 

I just connected the USB port from the back of the HV power monitor to the usb port of the laptop. Then I run the following python commands in sequence:

 import monsoon.HVPM as HVPM
 import monsoon.sampleEngine as sampleEngine
 import monsoon.Operations as op
 Mon = LVPM.Monsoon()
 Mon.setup_usb()

But after the last command, I get error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/monsoon-0.1.62-py2.7.egg/monsoon/HVPM.py", line 46, in setup_usb
    DEVICE = usb.core.find(idVendor=0x2AB9, idProduct=0x0001)
  File "build/bdist.macosx-10.12-intel/egg/usb/core.py", line 1263, in find
usb.core.NoBackendError: No backend available

It seems the USB is not connected correctly. 

How to identify the issue? Thanks

**Comment by andydonzelli** [comment]
Did you ever find a solution? I'm seeing the same error message.

**Comment by nniranjhana** [comment]
Thank you @andydonzelli!
