### ISSUE TITLE
Cannot find pmapi error

### ISSUE THREAD

**Issue by sf-wind** [msoon/PyMonsoon#22]
After I upgrade to 0.1.86, I get the following error.

```
Traceback (most recent call last):
  File "monsoon.py", line 1, in <module>
    import Monsoon.HVPM as HVPM
  File "/Users/feisun/python/monsoon/lib/python3.6/site-packages/Monsoon/HVPM.py", line 10, in <module>
    import pmapi
ModuleNotFoundError: No module named 'pmapi'
```

However, if I uncomment the
```
from Monsoon import pmapi
```
and comment 
```
import pmapi
```
I can launch the python driver.
https://github.com/msoon/PyMonsoon/blob/8cd5ce91a54139949c9b681cb404b4974131fb7a/Monsoon/HVPM.py#L10

Any reason why it is done so initially?

**Comment by andydonzelli** [comment]
Duplcate of https://github.com/msoon/PyMonsoon/issues/23
