### ISSUE TITLE
usb.core.USBError. How to set a rule for that?

### ISSUE THREAD

**Issue by hplinarian** [msoon/PyMonsoon#30]
I ran "Mon.setup_usb()" on raspberry pi 4
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.7/site-packages/Monsoon/HVPM.py", line 39, in setup_usb
    Protocol.Connect(op.HardwareModel.HVPM,serialno)
  File "/home/pi/.local/lib/python3.7/site-packages/Monsoon/pmapi.py", line 52, in Connect
    connectedDeviceType = self.getValue(op.OpCodes.HardwareModel,2)
  File "/home/pi/.local/lib/python3.7/site-packages/Monsoon/pmapi.py", line 128, in getValue
    result = self.DEVICE.ctrl_transfer(op.Control_Codes.USB_IN_PACKET,op.Control_Codes.USB_SET_VALUE,0,wIndex,4,5000)
  File "/home/pi/.local/lib/python3.7/site-packages/usb/core.py", line 1025, in ctrl_transfer
    self._ctx.managed_open()
  File "/home/pi/.local/lib/python3.7/site-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/usb/core.py", line 120, in managed_open
    self.handle = self.backend.open_device(self.dev)
  File "/home/pi/.local/lib/python3.7/site-packages/usb/backend/libusb1.py", line 786, in open_device
    return _DeviceHandle(dev)
  File "/home/pi/.local/lib/python3.7/site-packages/usb/backend/libusb1.py", line 643, in __init__
    _check(_lib.libusb_open(self.devid, byref(self.handle)))
  File "/home/pi/.local/lib/python3.7/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 13] Access denied (insufficient permissions)

Seems I have to set a rule to let users access that. Would you please provide me with some instructions?

**Comment by hplinarian** [comment]
solved

**Comment by wuyushuwys** [comment]
Hi @hplinarian , may i ask how did you solve this error? it seems i have the same problem. Thanks

**Comment by wuyushuwys** [comment]
Hi all, for others may encounter this error, here is my solution.

1. You will need to find your device's *VendorID* and *ProductID* via `lsusb -vvv`
2. Create a rule under the folder `/etc/udev/rules.d/`, such as `sudo vim /etc/udev/rules.d/monsoon.rules`
3. add line below to the file
`ACTION=="add", SUBSYSTEMS=="usb", ATTRS{idVendor}=="<VendorID>", ATTRS{idProduct}=="ProductID", MODE="660", GROUP="plugdev"`
4. Reload the rule `sudo udevadm control --reload`
5. `sudo udevadm trigger`
6. unplug and replug the device, you will be all set.
